# CMake generated Testfile for 
# Source directory: D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import
# Build directory: D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cmake_import_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 16 2019" "-A" "" "-DCMAKE_CXX_COMPILER=D:/Software/Microsoft/Visual Studio/VS2019/Pro/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_DIR=D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json" "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/project")
  set_tests_properties(cmake_import_configure PROPERTIES  FIXTURES_SETUP "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;1;add_test;D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cmake_import_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 16 2019" "-A" "" "-DCMAKE_CXX_COMPILER=D:/Software/Microsoft/Visual Studio/VS2019/Pro/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_DIR=D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json" "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/project")
  set_tests_properties(cmake_import_configure PROPERTIES  FIXTURES_SETUP "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;1;add_test;D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cmake_import_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 16 2019" "-A" "" "-DCMAKE_CXX_COMPILER=D:/Software/Microsoft/Visual Studio/VS2019/Pro/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_DIR=D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json" "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/project")
  set_tests_properties(cmake_import_configure PROPERTIES  FIXTURES_SETUP "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;1;add_test;D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cmake_import_configure "C:/Program Files/CMake/bin/cmake.exe" "-G" "Visual Studio 16 2019" "-A" "" "-DCMAKE_CXX_COMPILER=D:/Software/Microsoft/Visual Studio/VS2019/Pro/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe" "-Dnlohmann_json_DIR=D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json" "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/project")
  set_tests_properties(cmake_import_configure PROPERTIES  FIXTURES_SETUP "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;1;add_test;D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;0;")
else()
  add_test(cmake_import_configure NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cmake_import_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_import_build PROPERTIES  FIXTURES_REQUIRED "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;9;add_test;D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cmake_import_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_import_build PROPERTIES  FIXTURES_REQUIRED "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;9;add_test;D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cmake_import_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_import_build PROPERTIES  FIXTURES_REQUIRED "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;9;add_test;D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cmake_import_build "C:/Program Files/CMake/bin/cmake.exe" "--build" ".")
  set_tests_properties(cmake_import_build PROPERTIES  FIXTURES_REQUIRED "cmake_import" LABELS "not_reproducible" _BACKTRACE_TRIPLES "D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;9;add_test;D:/Sources/Current Projects/Foxy/Foxy 1.XX.X/vendor/json/tests/cmake_import/CMakeLists.txt;0;")
else()
  add_test(cmake_import_build NOT_AVAILABLE)
endif()
